export const crosswords = [
    {
        title: "Zagadki Polski",
        solution: "BAŁTYK",
        answers: [
            { word: "OBRAZ", question: "CO SIĘ MALUJE PĘDZLEM?", shift: 0 },
            { word: "ANAKONDA", question: "WODNE ZWIERZĘ, PODOBNE DO KROKODYLA", shift: 0 },
            { word: "TŁUM", question: "DUŻO LUDZI", shift: 0 },
            { word: "TATA", question: "TWÓJ RODZIC OPRÓCZ MAMY", shift: 0 },
            { word: "STYL", question: "CSS DEFINIUJE X STRONY", shift: 0 },
            { word: "KRAKÓW", question: "DAWNA STOLICA POLSKI", shift: 0 },
        ],
        createdAt: "1970-01-01T00:00:00Z",
        lastModifiedAt: "1970-01-01T00:00:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#344556",
        solutionBorderColor: "#677845",
        answersBorderThickness: 3,
        solutionBorderThickness: 6,
        answersBackgroundColor: "#454545",
        solutionsBackgroundColor: "#121212",
        id: '123123123',
        size: 20,
        shouldShowAnswers: true,
        shouldShowQuestions: false,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Owocowe zagadki",
        solution: "JABŁKO",
        answers: [
            { word: "JAGODA", question: "MAŁY LEŚNY OWOC", shift: 0 },
            { word: "ANANAS", question: "EGZOTYCZNY OWOC Z ŁUSKAMI", shift: 0 },
            { word: "BÓB", question: "WARZYWO STRĄCZKOWE", shift: 0 },
            { word: "ŁÓDŹ", question: "MIASTO W POLSCE", shift: 0 },
            { word: "KOMPOT", question: "NAPÓJ Z OWOCÓW", shift: 0 },
            { word: "OLIWKA", question: "ZIELONY OWOC Z PESTKĄ", shift: 0 },
        ],
        createdAt: "1971-02-03T10:15:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#563412",
        solutionBorderColor: "#781245",
        id: '1231231234',
        answersBorderThickness: 2,
        solutionBorderThickness: 5,
        answersBackgroundColor: "#889944",
        solutionsBackgroundColor: "#442211",
        size: 15,
        shouldShowAnswers: false,
        shouldShowQuestions: true,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Zwierzęcy świat",
        solution: "KOT",
        answers: [
            { word: "KROWA", question: "DAJE MLEKO", shift: 0 },
            { word: "OSA", question: "LATAJĄCY OWAD", shift: 0 },
            { word: "TYGRYS", question: "WIELKI KOT W DŻUNGLI", shift: 0 },
        ],
        createdAt: "1972-05-06T12:30:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#222222",
        solutionBorderColor: "#555555",
        answersBorderThickness: 3,
        id: '1231231231',
        solutionBorderThickness: 4,
        answersBackgroundColor: "#AAAAAA",
        solutionsBackgroundColor: "#333333",
        size: 10,
        shouldShowAnswers: true,
        shouldShowQuestions: true,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Na morzu",
        solution: "STATEK",
        answers: [
            { word: "SŁOŃCE", question: "ŚWIECI NAD MORZEM", shift: 0 },
            { word: "TAMA", question: "BUDOWLA NA RZECE", shift: 0 },
            { word: "ATRAMENT", question: "UŻYWANY W PIÓRZE", shift: 0 },
            { word: "TRATWA", question: "PROSTA ŁÓDŹ", shift: 0 },
            { word: "EKRAN", question: "POKAZUJE OBRAZ", shift: 0 },
            { word: "KUTER", question: "MAŁY STATEK RYBACKI", shift: 0 },
        ],
        createdAt: "1973-07-12T08:45:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#126677",
        solutionBorderColor: "#AA4433",
        id: '1231231',
        answersBorderThickness: 1,
        solutionBorderThickness: 4,
        answersBackgroundColor: "#556677",
        solutionsBackgroundColor: "#334455",
        size: 25,
        shouldShowAnswers: false,
        shouldShowQuestions: false,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Warzywa w kuchni",
        solution: "CEBULA",
        answers: [
            { word: "CZOSNEK", question: "CZĘSTO RAZEM Z CEBULĄ", shift: 0 },
            { word: "EKRAN", question: "W KOMPUTERZE", shift: 0 },
            { word: "BURAK", question: "CZERWONE WARZYWO", shift: 0 },
            { word: "UCHO", question: "NARZĄD SŁUCHU", shift: 0 },
            { word: "LATARNIA", question: "ŚWIECI W NOCY", shift: 0 },
            { word: "APTEKA", question: "TU KUPISZ LEKARSTWA", shift: 0 },
        ],
        createdAt: "1974-03-14T09:10:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#774422",
        solutionBorderColor: "#558877",
        id: '123123123123123',
        answersBorderThickness: 2,
        solutionBorderThickness: 6,
        answersBackgroundColor: "#DDEEBB",
        solutionsBackgroundColor: "#443322",
        size: 30,
        shouldShowAnswers: true,
        shouldShowQuestions: false,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Planety",
        solution: "MARS",
        answers: [
            { word: "MEWA", question: "PTAK NAD MORZEM", shift: 0 },
            { word: "ANIOŁ", question: "POSTAĆ ZE SKRZYDŁAMI", shift: 0 },
            { word: "RZEKA", question: "PŁYNIE PRZEZ KRAJ", shift: 0 },
            { word: "SŁOŃCE", question: "GWIAZDA UKŁADU SŁONECZNEGO", shift: 0 },
        ],
        createdAt: "1975-11-21T16:00:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#992233",
        solutionBorderColor: "#442255",
        answersBorderThickness: 2,
        solutionBorderThickness: 5,
        id: '123123123678456',
        answersBackgroundColor: "#331144",
        solutionsBackgroundColor: "#551122",
        size: 12,
        shouldShowAnswers: false,
        shouldShowQuestions: true,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "W górach",
        solution: "TATRY",
        answers: [
            { word: "TURYŚCI", question: "ZWIEDZAJĄ GÓRY", shift: 0 },
            { word: "AUTOBUS", question: "ŚRODEK TRANSPORTU", shift: 0 },
            { word: "TRATWA", question: "PŁYWAJĄCA KONSTRUKCJA", shift: 0 },
            { word: "RAKI", question: "SPRZĘT WSPINACZKOWY", shift: 0 },
            { word: "YETI", question: "MITYCZNY STWÓR", shift: 0 },
        ],
        createdAt: "1976-08-05T20:20:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#445566",
        solutionBorderColor: "#223344",
        answersBorderThickness: 3,
        solutionBorderThickness: 4,
        id: '1231231232345656',
        answersBackgroundColor: "#778899",
        solutionsBackgroundColor: "#556677",
        size: 18,
        shouldShowAnswers: true,
        shouldShowQuestions: true,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "W szkole",
        solution: "DŁUGOPIS",
        answers: [
            { word: "DZIENNIK", question: "MA GO NAUCZYCIEL", shift: 0 },
            { word: "ŁAWKA", question: "SIEDZĄ NA NIEJ UCZNIOWIE", shift: 0 },
            { word: "UBRANIE", question: "NOSZONE CODZIENNIE", shift: 0 },
            { word: "GLOB", question: "MODEL ZIEMI", shift: 0 },
            { word: "OŁÓWEK", question: "DO PISANIA", shift: 0 },
            { word: "PLECAK", question: "NOSI SIĘ KSIĄŻKI", shift: 0 },
            { word: "INFORMATYKA", question: "PRZEDMIOT SZKOLNY", shift: 0 },
            { word: "SOWA", question: "PTAK NOCNY", shift: 0 },
        ],
        createdAt: "1977-09-09T07:50:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#113355",
        solutionBorderColor: "#226677",
        answersBorderThickness: 2,
        solutionBorderThickness: 6,
        answersBackgroundColor: "#445577",
        solutionsBackgroundColor: "#112233",
        id: '123123123243545645',
        size: 22,
        shouldShowAnswers: false,
        shouldShowQuestions: false,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Zimowe zagadki",
        solution: "LÓD",
        answers: [
            { word: "LATARKA", question: "ŚWIECI W CIEMNOŚCI", shift: 0 },
            { word: "OGIEŃ", question: "PRZECIWIEŃSTWO LODU", shift: 0 },
            { word: "DACH", question: "CZĘŚĆ DOMU", shift: 0 },
        ],
        createdAt: "1978-12-01T11:25:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#77AAFF",
        solutionBorderColor: "#225588",
        answersBorderThickness: 2,
        solutionBorderThickness: 4,
        answersBackgroundColor: "#BBDDF5",
        solutionsBackgroundColor: "#445566",
        id: '12312312323446785456546',
        size: 14,
        shouldShowAnswers: true,
        shouldShowQuestions: false,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Sportowe emocje",
        solution: "PIŁKA",
        answers: [
            { word: "PIĘŚĆ", question: "ZACIŚNIĘTA DŁOŃ", shift: 0 },
            { word: "IRYS", question: "KWIAT OGRODOWY", shift: 0 },
            { word: "ŁÓDŹ", question: "MIASTO W POLSCE", shift: 0 },
            { word: "KASK", question: "OCHRONA GŁOWY", shift: 0 },
            { word: "ANANAS", question: "EGZOTYCZNY OWOC", shift: 0 },
        ],
        createdAt: "1979-04-17T06:40:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#DD3322",
        solutionBorderColor: "#2244AA",
        answersBorderThickness: 2,
        solutionBorderThickness: 6,
        answersBackgroundColor: "#FFCCAA",
        id: '123123123abdv',
        solutionsBackgroundColor: "#AA3322",
        size: 27,
        shouldShowAnswers: false,
        shouldShowQuestions: true,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Na wsi",
        solution: "KURA",
        answers: [
            { word: "KOŃ", question: "ZWIERZĘ W STAJNI", shift: 0 },
            { word: "ULE", question: "DOM PSZCZÓŁ", shift: 0 },
            { word: "RYBA", question: "MIESZKA W WODZIE", shift: 0 },
            { word: "ANIOŁ", question: "ISTOTA NIEBIAŃSKA", shift: 0 },
        ],
        createdAt: "1980-06-25T19:05:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#AA8844",
        solutionBorderColor: "#442288",
        id: '123123123ergfdvvcvc',
        answersBorderThickness: 3,
        solutionBorderThickness: 5,
        answersBackgroundColor: "#FFEEC0",
        solutionsBackgroundColor: "#554433",
        size: 16,
        shouldShowAnswers: true,
        shouldShowQuestions: true,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Muzyka",
        solution: "GITARA",
        answers: [
            { word: "GIT", question: "NARZĘDZIE PROGRAMISTY", shift: 0 },
            { word: "IGŁA", question: "DO SZYCIA", shift: 0 },
            { word: "TAKT", question: "PODZIAŁ RYTMICZNY", shift: 0 },
            { word: "ARIA", question: "FRAGMENT OPERY", shift: 0 },
            { word: "RÓG", question: "INSTRUMENT DĘTY", shift: 0 },
            { word: "AKTOR", question: "GRA W FILMIE", shift: 0 },
        ],
        createdAt: "1981-10-30T15:55:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#334422",
        solutionBorderColor: "#775533",
        id: '123123123234dsf324fsdf',
        answersBorderThickness: 1,
        solutionBorderThickness: 4,
        answersBackgroundColor: "#223344",
        solutionsBackgroundColor: "#667788",
        size: 19,
        shouldShowAnswers: false,
        shouldShowQuestions: false,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Technologia",
        solution: "LAPTOP",
        answers: [
            { word: "LAMPA", question: "DAJE ŚWIATŁO", shift: 0 },
            { word: "ANTENA", question: "ŁAPIE SYGNAŁ", shift: 0 },
            { word: "TELEFON", question: "DZWOIMY Z NIEGO", shift: 0 },
            { word: "PROGRAM", question: "APLIKACJA KOMPUTEROWA", shift: 0 },
            { word: "OKNO", question: "ELEMENT BUDYNKU I SYSTEMIE", shift: 0 },
            { word: "PŁYTKA", question: "ELEMENT ELEKTRONIKI", shift: 0 },
        ],
        createdAt: "1982-02-11T13:35:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#666666",
        solutionBorderColor: "#FF6600",
        id: '123123123432redsf32f',
        answersBorderThickness: 3,
        solutionBorderThickness: 6,
        answersBackgroundColor: "#333333",
        solutionsBackgroundColor: "#000000",
        size: 23,
        shouldShowAnswers: true,
        shouldShowQuestions: false,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Kolory",
        solution: "CZARNY",
        answers: [
            { word: "CZAPKA", question: "NAKRYCIE GŁOWY", shift: 0 },
            { word: "ZEBRA", question: "AFRYKAŃSKIE ZWIERZĘ W PASKI", shift: 0 },
            { word: "ARBUZ", question: "DUŻY OWOC LETNI", shift: 0 },
            { word: "RAMA", question: "OBRAMOWANIE OBRAZU", shift: 0 },
            { word: "NOS", question: "NARZĄD WĘCHU", shift: 0 },
            { word: "YETI", question: "MITYCZNY STWÓR GÓRSKI", shift: 0 },
        ],
        createdAt: "1983-03-15T18:22:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#111111",
        id: '123123123234sdc32fdsc',
        solutionBorderColor: "#EEEEEE",
        answersBorderThickness: 2,
        solutionBorderThickness: 4,
        answersBackgroundColor: "#222222",
        solutionsBackgroundColor: "#444444",
        size: 11,
        shouldShowAnswers: false,
        shouldShowQuestions: true,
    },
    {
        lastModifiedAt: "1970-01-01T00:00:00Z",
        title: "Transport",
        solution: "SAMOLOT",
        answers: [
            { word: "SAMURAJ", question: "WOJOWNIK JAPOŃSKI", shift: 0 },
            { word: "AUTO", question: "POJAZD DROGOWY", shift: 0 },
            { word: "MOST", question: "ŁĄCZY DWA BRZEGI", shift: 0 },
            { word: "OKNO", question: "ELEMENT BUDYNKU", shift: 0 },
            { word: "LOKOMOTYWA", question: "POCIĄGOWY POJAZD", shift: 0 },
            { word: "OSA", question: "ŻĄDLĄCY OWAD", shift: 0 },
            { word: "TRAMWAJ", question: "POJAZD MIEJSKI", shift: 0 },
        ],
        createdAt: "1984-07-19T21:10:00Z",
        shouldShowIndexes: false,
        answersBorderColor: "#003366",
        solutionBorderColor: "#660033",
        answersBorderThickness: 3,
        id: '12312312323dscxv34',
        solutionBorderThickness: 6,
        answersBackgroundColor: "#99CCFF",
        solutionsBackgroundColor: "#330066",
        size: 28,
        shouldShowAnswers: true,
        shouldShowQuestions: false,
    }
];
